//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  projects: Projects;
  projectsConnection: ProjectsConnection;
  about: About;
  aboutConnection: AboutConnection;
  howIWork: HowIWork;
  howIWorkConnection: HowIWorkConnection;
  design: Design;
  designConnection: DesignConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjectsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjectsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectsFilter>;
};


export type QueryAboutArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAboutConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
};


export type QueryHowIWorkArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHowIWorkConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HowIWorkFilter>;
};


export type QueryDesignArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDesignConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DesignFilter>;
};

export type DocumentFilter = {
  projects?: InputMaybe<ProjectsFilter>;
  about?: InputMaybe<AboutFilter>;
  howIWork?: InputMaybe<HowIWorkFilter>;
  design?: InputMaybe<DesignFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Projects | About | HowIWork | Design | Folder;

export type ProjectsInfo = {
  __typename?: 'ProjectsInfo';
  about?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  place?: Maybe<Scalars['String']['output']>;
  client?: Maybe<Scalars['String']['output']>;
};

export type ProjectsBlocksHero = {
  __typename?: 'ProjectsBlocksHero';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
  aspectRatio?: Maybe<Scalars['String']['output']>;
  parallax?: Maybe<Scalars['Float']['output']>;
};

export type ProjectsBlocksGalleryImages = {
  __typename?: 'ProjectsBlocksGalleryImages';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
  aspectRatio?: Maybe<Scalars['String']['output']>;
};

export type ProjectsBlocksGallery = {
  __typename?: 'ProjectsBlocksGallery';
  columns?: Maybe<Scalars['String']['output']>;
  images?: Maybe<Array<Maybe<ProjectsBlocksGalleryImages>>>;
};

export type ProjectsBlocksVideo = {
  __typename?: 'ProjectsBlocksVideo';
  provider?: Maybe<Scalars['String']['output']>;
  src?: Maybe<Scalars['String']['output']>;
  id?: Maybe<Scalars['String']['output']>;
  poster?: Maybe<Scalars['String']['output']>;
  caption?: Maybe<Scalars['String']['output']>;
};

export type ProjectsBlocksText = {
  __typename?: 'ProjectsBlocksText';
  heading?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type ProjectsBlocks = ProjectsBlocksHero | ProjectsBlocksGallery | ProjectsBlocksVideo | ProjectsBlocksText;

export type Projects = Node & Document & {
  __typename?: 'Projects';
  slug: Scalars['String']['output'];
  title: Scalars['String']['output'];
  category?: Maybe<Scalars['String']['output']>;
  year?: Maybe<Scalars['Float']['output']>;
  cover?: Maybe<Scalars['String']['output']>;
  coverAspect?: Maybe<Scalars['String']['output']>;
  gridSize?: Maybe<Scalars['String']['output']>;
  gridOffset?: Maybe<Scalars['Float']['output']>;
  hidden?: Maybe<Scalars['Boolean']['output']>;
  backgroundColor?: Maybe<Scalars['String']['output']>;
  info?: Maybe<ProjectsInfo>;
  blocks?: Maybe<Array<Maybe<ProjectsBlocks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ProjectsInfoFilter = {
  about?: InputMaybe<StringFilter>;
  date?: InputMaybe<StringFilter>;
  place?: InputMaybe<StringFilter>;
  client?: InputMaybe<StringFilter>;
};

export type ProjectsBlocksHeroFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  aspectRatio?: InputMaybe<StringFilter>;
  parallax?: InputMaybe<NumberFilter>;
};

export type ProjectsBlocksGalleryImagesFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  aspectRatio?: InputMaybe<StringFilter>;
};

export type ProjectsBlocksGalleryFilter = {
  columns?: InputMaybe<StringFilter>;
  images?: InputMaybe<ProjectsBlocksGalleryImagesFilter>;
};

export type ProjectsBlocksVideoFilter = {
  provider?: InputMaybe<StringFilter>;
  src?: InputMaybe<StringFilter>;
  id?: InputMaybe<StringFilter>;
  poster?: InputMaybe<ImageFilter>;
  caption?: InputMaybe<StringFilter>;
};

export type ProjectsBlocksTextFilter = {
  heading?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type ProjectsBlocksFilter = {
  hero?: InputMaybe<ProjectsBlocksHeroFilter>;
  gallery?: InputMaybe<ProjectsBlocksGalleryFilter>;
  video?: InputMaybe<ProjectsBlocksVideoFilter>;
  text?: InputMaybe<ProjectsBlocksTextFilter>;
};

export type ProjectsFilter = {
  slug?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  year?: InputMaybe<NumberFilter>;
  cover?: InputMaybe<ImageFilter>;
  coverAspect?: InputMaybe<StringFilter>;
  gridSize?: InputMaybe<StringFilter>;
  gridOffset?: InputMaybe<NumberFilter>;
  hidden?: InputMaybe<BooleanFilter>;
  backgroundColor?: InputMaybe<StringFilter>;
  info?: InputMaybe<ProjectsInfoFilter>;
  blocks?: InputMaybe<ProjectsBlocksFilter>;
};

export type ProjectsConnectionEdges = {
  __typename?: 'ProjectsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Projects>;
};

export type ProjectsConnection = Connection & {
  __typename?: 'ProjectsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProjectsConnectionEdges>>>;
};

export type About = Node & Document & {
  __typename?: 'About';
  name?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  bio?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  portrait?: Maybe<Scalars['String']['output']>;
  clients?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  email?: Maybe<Scalars['String']['output']>;
  instagram?: Maybe<Scalars['String']['output']>;
  vimeo?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AboutFilter = {
  name?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  bio?: InputMaybe<StringFilter>;
  portrait?: InputMaybe<ImageFilter>;
  clients?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  instagram?: InputMaybe<StringFilter>;
  vimeo?: InputMaybe<StringFilter>;
};

export type AboutConnectionEdges = {
  __typename?: 'AboutConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<About>;
};

export type AboutConnection = Connection & {
  __typename?: 'AboutConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AboutConnectionEdges>>>;
};

export type HowIWorkSteps = {
  __typename?: 'HowIWorkSteps';
  number?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type HowIWorkCta = {
  __typename?: 'HowIWorkCta';
  text?: Maybe<Scalars['String']['output']>;
  link?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type HowIWork = Node & Document & {
  __typename?: 'HowIWork';
  title?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  steps?: Maybe<Array<Maybe<HowIWorkSteps>>>;
  cta?: Maybe<HowIWorkCta>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HowIWorkStepsFilter = {
  number?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type HowIWorkCtaFilter = {
  text?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type HowIWorkFilter = {
  title?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  steps?: InputMaybe<HowIWorkStepsFilter>;
  cta?: InputMaybe<HowIWorkCtaFilter>;
};

export type HowIWorkConnectionEdges = {
  __typename?: 'HowIWorkConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<HowIWork>;
};

export type HowIWorkConnection = Connection & {
  __typename?: 'HowIWorkConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HowIWorkConnectionEdges>>>;
};

export type DesignColors = {
  __typename?: 'DesignColors';
  background?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
  textMuted?: Maybe<Scalars['String']['output']>;
  textBright?: Maybe<Scalars['String']['output']>;
  border?: Maybe<Scalars['String']['output']>;
  labelColor?: Maybe<Scalars['String']['output']>;
};

export type DesignTypographyHeadings = {
  __typename?: 'DesignTypographyHeadings';
  weight?: Maybe<Scalars['String']['output']>;
  letterSpacing?: Maybe<Scalars['String']['output']>;
  lineHeight?: Maybe<Scalars['String']['output']>;
};

export type DesignTypographyLabels = {
  __typename?: 'DesignTypographyLabels';
  size?: Maybe<Scalars['String']['output']>;
  letterSpacing?: Maybe<Scalars['String']['output']>;
};

export type DesignTypographyBody = {
  __typename?: 'DesignTypographyBody';
  size?: Maybe<Scalars['String']['output']>;
  lineHeight?: Maybe<Scalars['String']['output']>;
};

export type DesignTypography = {
  __typename?: 'DesignTypography';
  sans?: Maybe<Scalars['String']['output']>;
  display?: Maybe<Scalars['String']['output']>;
  headings?: Maybe<DesignTypographyHeadings>;
  labels?: Maybe<DesignTypographyLabels>;
  body?: Maybe<DesignTypographyBody>;
};

export type DesignTextBlock = {
  __typename?: 'DesignTextBlock';
  headingSize?: Maybe<Scalars['String']['output']>;
  headingWeight?: Maybe<Scalars['String']['output']>;
  headingLetterSpacing?: Maybe<Scalars['String']['output']>;
  headingLineHeight?: Maybe<Scalars['String']['output']>;
  bodySize?: Maybe<Scalars['String']['output']>;
  bodyLineHeight?: Maybe<Scalars['String']['output']>;
  maxWidth?: Maybe<Scalars['String']['output']>;
  gap?: Maybe<Scalars['String']['output']>;
};

export type DesignButtons = {
  __typename?: 'DesignButtons';
  fontSize?: Maybe<Scalars['String']['output']>;
  letterSpacing?: Maybe<Scalars['String']['output']>;
  paddingV?: Maybe<Scalars['String']['output']>;
  paddingH?: Maybe<Scalars['String']['output']>;
};

export type Design = Node & Document & {
  __typename?: 'Design';
  colors?: Maybe<DesignColors>;
  typography?: Maybe<DesignTypography>;
  textBlock?: Maybe<DesignTextBlock>;
  buttons?: Maybe<DesignButtons>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DesignColorsFilter = {
  background?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  textMuted?: InputMaybe<StringFilter>;
  textBright?: InputMaybe<StringFilter>;
  border?: InputMaybe<StringFilter>;
  labelColor?: InputMaybe<StringFilter>;
};

export type DesignTypographyHeadingsFilter = {
  weight?: InputMaybe<StringFilter>;
  letterSpacing?: InputMaybe<StringFilter>;
  lineHeight?: InputMaybe<StringFilter>;
};

export type DesignTypographyLabelsFilter = {
  size?: InputMaybe<StringFilter>;
  letterSpacing?: InputMaybe<StringFilter>;
};

export type DesignTypographyBodyFilter = {
  size?: InputMaybe<StringFilter>;
  lineHeight?: InputMaybe<StringFilter>;
};

export type DesignTypographyFilter = {
  sans?: InputMaybe<StringFilter>;
  display?: InputMaybe<StringFilter>;
  headings?: InputMaybe<DesignTypographyHeadingsFilter>;
  labels?: InputMaybe<DesignTypographyLabelsFilter>;
  body?: InputMaybe<DesignTypographyBodyFilter>;
};

export type DesignTextBlockFilter = {
  headingSize?: InputMaybe<StringFilter>;
  headingWeight?: InputMaybe<StringFilter>;
  headingLetterSpacing?: InputMaybe<StringFilter>;
  headingLineHeight?: InputMaybe<StringFilter>;
  bodySize?: InputMaybe<StringFilter>;
  bodyLineHeight?: InputMaybe<StringFilter>;
  maxWidth?: InputMaybe<StringFilter>;
  gap?: InputMaybe<StringFilter>;
};

export type DesignButtonsFilter = {
  fontSize?: InputMaybe<StringFilter>;
  letterSpacing?: InputMaybe<StringFilter>;
  paddingV?: InputMaybe<StringFilter>;
  paddingH?: InputMaybe<StringFilter>;
};

export type DesignFilter = {
  colors?: InputMaybe<DesignColorsFilter>;
  typography?: InputMaybe<DesignTypographyFilter>;
  textBlock?: InputMaybe<DesignTextBlockFilter>;
  buttons?: InputMaybe<DesignButtonsFilter>;
};

export type DesignConnectionEdges = {
  __typename?: 'DesignConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Design>;
};

export type DesignConnection = Connection & {
  __typename?: 'DesignConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DesignConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateProjects: Projects;
  createProjects: Projects;
  updateAbout: About;
  createAbout: About;
  updateHowIWork: HowIWork;
  createHowIWork: HowIWork;
  updateDesign: Design;
  createDesign: Design;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateProjectsArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectsMutation;
};


export type MutationCreateProjectsArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectsMutation;
};


export type MutationUpdateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationCreateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationUpdateHowIWorkArgs = {
  relativePath: Scalars['String']['input'];
  params: HowIWorkMutation;
};


export type MutationCreateHowIWorkArgs = {
  relativePath: Scalars['String']['input'];
  params: HowIWorkMutation;
};


export type MutationUpdateDesignArgs = {
  relativePath: Scalars['String']['input'];
  params: DesignMutation;
};


export type MutationCreateDesignArgs = {
  relativePath: Scalars['String']['input'];
  params: DesignMutation;
};

export type DocumentUpdateMutation = {
  projects?: InputMaybe<ProjectsMutation>;
  about?: InputMaybe<AboutMutation>;
  howIWork?: InputMaybe<HowIWorkMutation>;
  design?: InputMaybe<DesignMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  projects?: InputMaybe<ProjectsMutation>;
  about?: InputMaybe<AboutMutation>;
  howIWork?: InputMaybe<HowIWorkMutation>;
  design?: InputMaybe<DesignMutation>;
};

export type ProjectsInfoMutation = {
  about?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  place?: InputMaybe<Scalars['String']['input']>;
  client?: InputMaybe<Scalars['String']['input']>;
};

export type ProjectsBlocksHeroMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
  aspectRatio?: InputMaybe<Scalars['String']['input']>;
  parallax?: InputMaybe<Scalars['Float']['input']>;
};

export type ProjectsBlocksGalleryImagesMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
  aspectRatio?: InputMaybe<Scalars['String']['input']>;
};

export type ProjectsBlocksGalleryMutation = {
  columns?: InputMaybe<Scalars['String']['input']>;
  images?: InputMaybe<Array<InputMaybe<ProjectsBlocksGalleryImagesMutation>>>;
};

export type ProjectsBlocksVideoMutation = {
  provider?: InputMaybe<Scalars['String']['input']>;
  src?: InputMaybe<Scalars['String']['input']>;
  id?: InputMaybe<Scalars['String']['input']>;
  poster?: InputMaybe<Scalars['String']['input']>;
  caption?: InputMaybe<Scalars['String']['input']>;
};

export type ProjectsBlocksTextMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type ProjectsBlocksMutation = {
  hero?: InputMaybe<ProjectsBlocksHeroMutation>;
  gallery?: InputMaybe<ProjectsBlocksGalleryMutation>;
  video?: InputMaybe<ProjectsBlocksVideoMutation>;
  text?: InputMaybe<ProjectsBlocksTextMutation>;
};

export type ProjectsMutation = {
  slug?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['Float']['input']>;
  cover?: InputMaybe<Scalars['String']['input']>;
  coverAspect?: InputMaybe<Scalars['String']['input']>;
  gridSize?: InputMaybe<Scalars['String']['input']>;
  gridOffset?: InputMaybe<Scalars['Float']['input']>;
  hidden?: InputMaybe<Scalars['Boolean']['input']>;
  backgroundColor?: InputMaybe<Scalars['String']['input']>;
  info?: InputMaybe<ProjectsInfoMutation>;
  blocks?: InputMaybe<Array<InputMaybe<ProjectsBlocksMutation>>>;
};

export type AboutMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  portrait?: InputMaybe<Scalars['String']['input']>;
  clients?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  email?: InputMaybe<Scalars['String']['input']>;
  instagram?: InputMaybe<Scalars['String']['input']>;
  vimeo?: InputMaybe<Scalars['String']['input']>;
};

export type HowIWorkStepsMutation = {
  number?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type HowIWorkCtaMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
  link?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type HowIWorkMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  steps?: InputMaybe<Array<InputMaybe<HowIWorkStepsMutation>>>;
  cta?: InputMaybe<HowIWorkCtaMutation>;
};

export type DesignColorsMutation = {
  background?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
  textMuted?: InputMaybe<Scalars['String']['input']>;
  textBright?: InputMaybe<Scalars['String']['input']>;
  border?: InputMaybe<Scalars['String']['input']>;
  labelColor?: InputMaybe<Scalars['String']['input']>;
};

export type DesignTypographyHeadingsMutation = {
  weight?: InputMaybe<Scalars['String']['input']>;
  letterSpacing?: InputMaybe<Scalars['String']['input']>;
  lineHeight?: InputMaybe<Scalars['String']['input']>;
};

export type DesignTypographyLabelsMutation = {
  size?: InputMaybe<Scalars['String']['input']>;
  letterSpacing?: InputMaybe<Scalars['String']['input']>;
};

export type DesignTypographyBodyMutation = {
  size?: InputMaybe<Scalars['String']['input']>;
  lineHeight?: InputMaybe<Scalars['String']['input']>;
};

export type DesignTypographyMutation = {
  sans?: InputMaybe<Scalars['String']['input']>;
  display?: InputMaybe<Scalars['String']['input']>;
  headings?: InputMaybe<DesignTypographyHeadingsMutation>;
  labels?: InputMaybe<DesignTypographyLabelsMutation>;
  body?: InputMaybe<DesignTypographyBodyMutation>;
};

export type DesignTextBlockMutation = {
  headingSize?: InputMaybe<Scalars['String']['input']>;
  headingWeight?: InputMaybe<Scalars['String']['input']>;
  headingLetterSpacing?: InputMaybe<Scalars['String']['input']>;
  headingLineHeight?: InputMaybe<Scalars['String']['input']>;
  bodySize?: InputMaybe<Scalars['String']['input']>;
  bodyLineHeight?: InputMaybe<Scalars['String']['input']>;
  maxWidth?: InputMaybe<Scalars['String']['input']>;
  gap?: InputMaybe<Scalars['String']['input']>;
};

export type DesignButtonsMutation = {
  fontSize?: InputMaybe<Scalars['String']['input']>;
  letterSpacing?: InputMaybe<Scalars['String']['input']>;
  paddingV?: InputMaybe<Scalars['String']['input']>;
  paddingH?: InputMaybe<Scalars['String']['input']>;
};

export type DesignMutation = {
  colors?: InputMaybe<DesignColorsMutation>;
  typography?: InputMaybe<DesignTypographyMutation>;
  textBlock?: InputMaybe<DesignTextBlockMutation>;
  buttons?: InputMaybe<DesignButtonsMutation>;
};

export type ProjectsPartsFragment = { __typename: 'Projects', slug: string, title: string, category?: string | null, year?: number | null, cover?: string | null, coverAspect?: string | null, gridSize?: string | null, gridOffset?: number | null, hidden?: boolean | null, backgroundColor?: string | null, info?: { __typename: 'ProjectsInfo', about?: string | null, date?: string | null, place?: string | null, client?: string | null } | null, blocks?: Array<{ __typename: 'ProjectsBlocksHero', src?: string | null, alt?: string | null, aspectRatio?: string | null, parallax?: number | null } | { __typename: 'ProjectsBlocksGallery', columns?: string | null, images?: Array<{ __typename: 'ProjectsBlocksGalleryImages', src?: string | null, alt?: string | null, aspectRatio?: string | null } | null> | null } | { __typename: 'ProjectsBlocksVideo', provider?: string | null, src?: string | null, id?: string | null, poster?: string | null, caption?: string | null } | { __typename: 'ProjectsBlocksText', heading?: string | null, body?: string | null } | null> | null };

export type AboutPartsFragment = { __typename: 'About', name?: string | null, title?: string | null, bio?: Array<string | null> | null, portrait?: string | null, clients?: Array<string | null> | null, email?: string | null, instagram?: string | null, vimeo?: string | null };

export type HowIWorkPartsFragment = { __typename: 'HowIWork', title?: string | null, intro?: string | null, steps?: Array<{ __typename: 'HowIWorkSteps', number?: string | null, title?: string | null, body?: string | null } | null> | null, cta?: { __typename: 'HowIWorkCta', text?: string | null, link?: string | null, label?: string | null } | null };

export type DesignPartsFragment = { __typename: 'Design', colors?: { __typename: 'DesignColors', background?: string | null, text?: string | null, textMuted?: string | null, textBright?: string | null, border?: string | null, labelColor?: string | null } | null, typography?: { __typename: 'DesignTypography', sans?: string | null, display?: string | null, headings?: { __typename: 'DesignTypographyHeadings', weight?: string | null, letterSpacing?: string | null, lineHeight?: string | null } | null, labels?: { __typename: 'DesignTypographyLabels', size?: string | null, letterSpacing?: string | null } | null, body?: { __typename: 'DesignTypographyBody', size?: string | null, lineHeight?: string | null } | null } | null, textBlock?: { __typename: 'DesignTextBlock', headingSize?: string | null, headingWeight?: string | null, headingLetterSpacing?: string | null, headingLineHeight?: string | null, bodySize?: string | null, bodyLineHeight?: string | null, maxWidth?: string | null, gap?: string | null } | null, buttons?: { __typename: 'DesignButtons', fontSize?: string | null, letterSpacing?: string | null, paddingV?: string | null, paddingH?: string | null } | null };

export type ProjectsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProjectsQuery = { __typename?: 'Query', projects: { __typename: 'Projects', id: string, slug: string, title: string, category?: string | null, year?: number | null, cover?: string | null, coverAspect?: string | null, gridSize?: string | null, gridOffset?: number | null, hidden?: boolean | null, backgroundColor?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, info?: { __typename: 'ProjectsInfo', about?: string | null, date?: string | null, place?: string | null, client?: string | null } | null, blocks?: Array<{ __typename: 'ProjectsBlocksHero', src?: string | null, alt?: string | null, aspectRatio?: string | null, parallax?: number | null } | { __typename: 'ProjectsBlocksGallery', columns?: string | null, images?: Array<{ __typename: 'ProjectsBlocksGalleryImages', src?: string | null, alt?: string | null, aspectRatio?: string | null } | null> | null } | { __typename: 'ProjectsBlocksVideo', provider?: string | null, src?: string | null, id?: string | null, poster?: string | null, caption?: string | null } | { __typename: 'ProjectsBlocksText', heading?: string | null, body?: string | null } | null> | null } };

export type ProjectsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectsFilter>;
}>;


export type ProjectsConnectionQuery = { __typename?: 'Query', projectsConnection: { __typename?: 'ProjectsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProjectsConnectionEdges', cursor: string, node?: { __typename: 'Projects', id: string, slug: string, title: string, category?: string | null, year?: number | null, cover?: string | null, coverAspect?: string | null, gridSize?: string | null, gridOffset?: number | null, hidden?: boolean | null, backgroundColor?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, info?: { __typename: 'ProjectsInfo', about?: string | null, date?: string | null, place?: string | null, client?: string | null } | null, blocks?: Array<{ __typename: 'ProjectsBlocksHero', src?: string | null, alt?: string | null, aspectRatio?: string | null, parallax?: number | null } | { __typename: 'ProjectsBlocksGallery', columns?: string | null, images?: Array<{ __typename: 'ProjectsBlocksGalleryImages', src?: string | null, alt?: string | null, aspectRatio?: string | null } | null> | null } | { __typename: 'ProjectsBlocksVideo', provider?: string | null, src?: string | null, id?: string | null, poster?: string | null, caption?: string | null } | { __typename: 'ProjectsBlocksText', heading?: string | null, body?: string | null } | null> | null } | null } | null> | null } };

export type AboutQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AboutQuery = { __typename?: 'Query', about: { __typename: 'About', id: string, name?: string | null, title?: string | null, bio?: Array<string | null> | null, portrait?: string | null, clients?: Array<string | null> | null, email?: string | null, instagram?: string | null, vimeo?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type AboutConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
}>;


export type AboutConnectionQuery = { __typename?: 'Query', aboutConnection: { __typename?: 'AboutConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AboutConnectionEdges', cursor: string, node?: { __typename: 'About', id: string, name?: string | null, title?: string | null, bio?: Array<string | null> | null, portrait?: string | null, clients?: Array<string | null> | null, email?: string | null, instagram?: string | null, vimeo?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type HowIWorkQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HowIWorkQuery = { __typename?: 'Query', howIWork: { __typename: 'HowIWork', id: string, title?: string | null, intro?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, steps?: Array<{ __typename: 'HowIWorkSteps', number?: string | null, title?: string | null, body?: string | null } | null> | null, cta?: { __typename: 'HowIWorkCta', text?: string | null, link?: string | null, label?: string | null } | null } };

export type HowIWorkConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HowIWorkFilter>;
}>;


export type HowIWorkConnectionQuery = { __typename?: 'Query', howIWorkConnection: { __typename?: 'HowIWorkConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HowIWorkConnectionEdges', cursor: string, node?: { __typename: 'HowIWork', id: string, title?: string | null, intro?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, steps?: Array<{ __typename: 'HowIWorkSteps', number?: string | null, title?: string | null, body?: string | null } | null> | null, cta?: { __typename: 'HowIWorkCta', text?: string | null, link?: string | null, label?: string | null } | null } | null } | null> | null } };

export type DesignQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type DesignQuery = { __typename?: 'Query', design: { __typename: 'Design', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, colors?: { __typename: 'DesignColors', background?: string | null, text?: string | null, textMuted?: string | null, textBright?: string | null, border?: string | null, labelColor?: string | null } | null, typography?: { __typename: 'DesignTypography', sans?: string | null, display?: string | null, headings?: { __typename: 'DesignTypographyHeadings', weight?: string | null, letterSpacing?: string | null, lineHeight?: string | null } | null, labels?: { __typename: 'DesignTypographyLabels', size?: string | null, letterSpacing?: string | null } | null, body?: { __typename: 'DesignTypographyBody', size?: string | null, lineHeight?: string | null } | null } | null, textBlock?: { __typename: 'DesignTextBlock', headingSize?: string | null, headingWeight?: string | null, headingLetterSpacing?: string | null, headingLineHeight?: string | null, bodySize?: string | null, bodyLineHeight?: string | null, maxWidth?: string | null, gap?: string | null } | null, buttons?: { __typename: 'DesignButtons', fontSize?: string | null, letterSpacing?: string | null, paddingV?: string | null, paddingH?: string | null } | null } };

export type DesignConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DesignFilter>;
}>;


export type DesignConnectionQuery = { __typename?: 'Query', designConnection: { __typename?: 'DesignConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'DesignConnectionEdges', cursor: string, node?: { __typename: 'Design', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, colors?: { __typename: 'DesignColors', background?: string | null, text?: string | null, textMuted?: string | null, textBright?: string | null, border?: string | null, labelColor?: string | null } | null, typography?: { __typename: 'DesignTypography', sans?: string | null, display?: string | null, headings?: { __typename: 'DesignTypographyHeadings', weight?: string | null, letterSpacing?: string | null, lineHeight?: string | null } | null, labels?: { __typename: 'DesignTypographyLabels', size?: string | null, letterSpacing?: string | null } | null, body?: { __typename: 'DesignTypographyBody', size?: string | null, lineHeight?: string | null } | null } | null, textBlock?: { __typename: 'DesignTextBlock', headingSize?: string | null, headingWeight?: string | null, headingLetterSpacing?: string | null, headingLineHeight?: string | null, bodySize?: string | null, bodyLineHeight?: string | null, maxWidth?: string | null, gap?: string | null } | null, buttons?: { __typename: 'DesignButtons', fontSize?: string | null, letterSpacing?: string | null, paddingV?: string | null, paddingH?: string | null } | null } | null } | null> | null } };

export const ProjectsPartsFragmentDoc = gql`
    fragment ProjectsParts on Projects {
  __typename
  slug
  title
  category
  year
  cover
  coverAspect
  gridSize
  gridOffset
  hidden
  backgroundColor
  info {
    __typename
    about
    date
    place
    client
  }
  blocks {
    __typename
    ... on ProjectsBlocksHero {
      src
      alt
      aspectRatio
      parallax
    }
    ... on ProjectsBlocksGallery {
      columns
      images {
        __typename
        src
        alt
        aspectRatio
      }
    }
    ... on ProjectsBlocksVideo {
      provider
      src
      id
      poster
      caption
    }
    ... on ProjectsBlocksText {
      heading
      body
    }
  }
}
    `;
export const AboutPartsFragmentDoc = gql`
    fragment AboutParts on About {
  __typename
  name
  title
  bio
  portrait
  clients
  email
  instagram
  vimeo
}
    `;
export const HowIWorkPartsFragmentDoc = gql`
    fragment HowIWorkParts on HowIWork {
  __typename
  title
  intro
  steps {
    __typename
    number
    title
    body
  }
  cta {
    __typename
    text
    link
    label
  }
}
    `;
export const DesignPartsFragmentDoc = gql`
    fragment DesignParts on Design {
  __typename
  colors {
    __typename
    background
    text
    textMuted
    textBright
    border
    labelColor
  }
  typography {
    __typename
    sans
    display
    headings {
      __typename
      weight
      letterSpacing
      lineHeight
    }
    labels {
      __typename
      size
      letterSpacing
    }
    body {
      __typename
      size
      lineHeight
    }
  }
  textBlock {
    __typename
    headingSize
    headingWeight
    headingLetterSpacing
    headingLineHeight
    bodySize
    bodyLineHeight
    maxWidth
    gap
  }
  buttons {
    __typename
    fontSize
    letterSpacing
    paddingV
    paddingH
  }
}
    `;
export const ProjectsDocument = gql`
    query projects($relativePath: String!) {
  projects(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProjectsParts
  }
}
    ${ProjectsPartsFragmentDoc}`;
export const ProjectsConnectionDocument = gql`
    query projectsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProjectsFilter) {
  projectsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProjectsParts
      }
    }
  }
}
    ${ProjectsPartsFragmentDoc}`;
export const AboutDocument = gql`
    query about($relativePath: String!) {
  about(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AboutParts
  }
}
    ${AboutPartsFragmentDoc}`;
export const AboutConnectionDocument = gql`
    query aboutConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AboutFilter) {
  aboutConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AboutParts
      }
    }
  }
}
    ${AboutPartsFragmentDoc}`;
export const HowIWorkDocument = gql`
    query howIWork($relativePath: String!) {
  howIWork(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HowIWorkParts
  }
}
    ${HowIWorkPartsFragmentDoc}`;
export const HowIWorkConnectionDocument = gql`
    query howIWorkConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HowIWorkFilter) {
  howIWorkConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HowIWorkParts
      }
    }
  }
}
    ${HowIWorkPartsFragmentDoc}`;
export const DesignDocument = gql`
    query design($relativePath: String!) {
  design(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...DesignParts
  }
}
    ${DesignPartsFragmentDoc}`;
export const DesignConnectionDocument = gql`
    query designConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: DesignFilter) {
  designConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...DesignParts
      }
    }
  }
}
    ${DesignPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      projects(variables: ProjectsQueryVariables, options?: C): Promise<{data: ProjectsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectsQueryVariables, query: string}> {
        return requester<{data: ProjectsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectsQueryVariables, query: string}, ProjectsQueryVariables>(ProjectsDocument, variables, options);
      },
    projectsConnection(variables?: ProjectsConnectionQueryVariables, options?: C): Promise<{data: ProjectsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectsConnectionQueryVariables, query: string}> {
        return requester<{data: ProjectsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectsConnectionQueryVariables, query: string}, ProjectsConnectionQueryVariables>(ProjectsConnectionDocument, variables, options);
      },
    about(variables: AboutQueryVariables, options?: C): Promise<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}> {
        return requester<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}, AboutQueryVariables>(AboutDocument, variables, options);
      },
    aboutConnection(variables?: AboutConnectionQueryVariables, options?: C): Promise<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}> {
        return requester<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}, AboutConnectionQueryVariables>(AboutConnectionDocument, variables, options);
      },
    howIWork(variables: HowIWorkQueryVariables, options?: C): Promise<{data: HowIWorkQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HowIWorkQueryVariables, query: string}> {
        return requester<{data: HowIWorkQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HowIWorkQueryVariables, query: string}, HowIWorkQueryVariables>(HowIWorkDocument, variables, options);
      },
    howIWorkConnection(variables?: HowIWorkConnectionQueryVariables, options?: C): Promise<{data: HowIWorkConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HowIWorkConnectionQueryVariables, query: string}> {
        return requester<{data: HowIWorkConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HowIWorkConnectionQueryVariables, query: string}, HowIWorkConnectionQueryVariables>(HowIWorkConnectionDocument, variables, options);
      },
    design(variables: DesignQueryVariables, options?: C): Promise<{data: DesignQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DesignQueryVariables, query: string}> {
        return requester<{data: DesignQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DesignQueryVariables, query: string}, DesignQueryVariables>(DesignDocument, variables, options);
      },
    designConnection(variables?: DesignConnectionQueryVariables, options?: C): Promise<{data: DesignConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DesignConnectionQueryVariables, query: string}> {
        return requester<{data: DesignConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DesignConnectionQueryVariables, query: string}, DesignConnectionQueryVariables>(DesignConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.2/content/61301fe6-2380-40de-8e9b-0e70abab07df/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  